export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  odooUrl: process.env.ODOO_URL ?? "",
  odooDb: process.env.ODOO_DB ?? "",
  odooUsername: process.env.ODOO_USERNAME ?? process.env.ODOO_LOGIN ?? "",
  odooPassword: process.env.ODOO_PASSWORD ?? process.env.ODOO_API_KEY ?? "",
  odooPackProductId: process.env.ODOO_PACK_PRODUCT_ID ?? "",
  odooPackProductCode: process.env.ODOO_PACK_PRODUCT_CODE ?? "AQUASACHET_PACK",
  odooPublicApi: process.env.ODOO_PUBLIC_API === "true",
};
